// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOfODy_KnXgqGy2choRN1QDR1SG2TBJks',
    appId: '1:782589507666:web:f73b8677c42ff20986c78b',
    messagingSenderId: '782589507666',
    projectId: 'servifast-be40d',
    authDomain: 'servifast-be40d.firebaseapp.com',
    storageBucket: 'servifast-be40d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPlH0t67WYk3QQ3r6faxSDiZFrADv_sQY',
    appId: '1:782589507666:android:6fe7a14c23fe3b7a86c78b',
    messagingSenderId: '782589507666',
    projectId: 'servifast-be40d',
    storageBucket: 'servifast-be40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLH8un2Z4sRilZ4-yuadUVmjcaXwELnc',
    appId: '1:782589507666:ios:8186c99b5eca7b1886c78b',
    messagingSenderId: '782589507666',
    projectId: 'servifast-be40d',
    storageBucket: 'servifast-be40d.firebasestorage.app',
    iosBundleId: 'com.example.servifastApp',
  );
}
